default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['DB_NAME']%>
  username: <%= ENV['DB_USER']%>
  password: <%= ENV['DB_PASSWORD']%>
  host:     <%= ENV['DB_HOST']%>

development:
  <<: *default
  database: marketplace_development

test:
  <<: *default
  database: marketplace_test

production:
  <<: *default
  database: marketplace_production
